name: aparcabicis4
description: "Sistema móvil de reserva y control de plazas de aparcamiento inteligente para bicicletas."
publish_to: 'none'
version: 1.0.0+10

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  geolocator: ^10.1.0
  permission_handler: ^11.1.0
  url_launcher: ^6.2.1
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  http: ^1.5.0
  change_app_package_name: ^1.5.0
  flutter_launcher_icons: ^0.14.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icono_definitivo.png"
  remove_alpha_ios: true
  min_sdk_android: 21

flutter:
  uses-material-design: true
